version: '3.5'

services:
  postgres:
   container_name: pg-codesh
   image: postgres
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: root
    POSTGRES_DB: codeshDb
   ports:
    - "5432:5432"